/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package praktek6;

import praktek6.Models.DataPassword;
import praktek6.Models.MainPage;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args)throws Exception {
        DataPassword.loadCSVData();
        MainPage mp = new MainPage(50);
        mp.draw();
    }
}
