/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package praktek45;

import praktek45.Models.DataPassword;
import praktek45.Models.MainPage;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args)throws Exception {
        DataPassword.loadCSVData();
        new MainPage("Aplikasi Password Vault", 70).draw();
    }
}
